name: Data Science Images CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Data Science image
      run: docker build -f data-science/Dockerfile -t data-science:latest .

    - name: Build Data Science GPU image
      run: docker build -f data-science-gpu/Dockerfile -t data-science-gpu:latest .
